/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CaptainsRouteImport } from './routes/captains'
import { Route as IndexRouteImport } from './routes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsRoute = CaptainsRouteImport.update({
  id: '/captains',
  path: '/captains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/captains' | '/events' | '/live-scores' | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/captains' | '/events' | '/live-scores' | '/register'
  id: '__root__' | '/' | '/captains' | '/events' | '/live-scores' | '/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptainsRoute: typeof CaptainsRoute
  EventsRoute: typeof EventsRoute
  LiveScoresRoute: typeof LiveScoresRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains': {
      id: '/captains'
      path: '/captains'
      fullPath: '/captains'
      preLoaderRoute: typeof CaptainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptainsRoute: CaptainsRoute,
  EventsRoute: EventsRoute,
  LiveScoresRoute: LiveScoresRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
